server:
  port: 9090
---
spring:
  cloud:
    gateway:
      routes:
        - id: user-client-pa
          uri: http://localhost:8083
          predicates:
            - Path=/user/**
        - id: payroll-client-pa
          uri: http://localhost:8082
          predicates:
            - Path=/payroll/**
        - id: authentication-client-pa
          uri: http://localhost:8084
          predicates:
          - Path=/authenticate/*
          - Path=/verify/*
    